#Weighted Least Square

In measurements of certain parameters, certain measurements are more accurate than others because these may have come from a better sensor. For example, a number of our resistance measurements could have come from a much more expensive multi-meter than the others. Let's begin by using the following general notation.   

We'll have a set of $m$ measurements that are related to a set of n unknown parameters through a linear model

$\mathbf{y} = \mathbf{H}x+\mathbf{v}$.  

Let us assume that each noise term has a different variance, we can define our noise covariance as follows.

$ \mathbf{R} = \begin{pmatrix}
\sigma^2_1 & 0 &... & 0 \\ 
0 & \sigma^2_2 & ... &0\\ 
.. & .. & ... &... \\ 
0 & 0 & ... & \sigma^2_m \\
\end{pmatrix}$

The loss function for the WLS methos is sum of the weighted squared error. The readings from the reliable sensors are given more weightage. We also know that reliable sensor would have low variance. This gives us an idea of using the inverse of the variance as weights.  


$$ \mathcal{L}_{WLS} = \frac{e_1}{\sigma_1^2}+\frac{e_2}{\sigma_2^2}+ ... + \frac{e_m}{\sigma_m^2} $$

We can write the above expression in matrix form as,  
$\mathcal{L}_{WLS} = \mathbf{e^TR^{-1}e}$  
Using the usual procedure we get the best estimation of the parameters $\mathbf{x}$ is given by:  
$\hat{\mathbf{x}} = \left(\mathbf{H^TR^{-1}H}\right)^{-1}\mathbf{H^TR^{-1}y}$

### Example -1 One Parameter with weights
-----
Estimate the resistance of an electrical component using six observations. These measurements are obtained using two different multimeters with different standard deviations as specified in the table below:

| R(σ=20 Ω) | R (σ=6 Ω) |
|----------|----------|
| 1048     | 992      |
| 1074     | 988      |
| 960      | 1008     |




**Solution**  

The measurement covariance matrix would be

$ \mathbf{R} = \begin{pmatrix}
\sigma^2_1&0&0&0&0&0 \\ 
0&\sigma^2_2&0&0&0&0\\
0&0&\sigma^2_1&0&0&0\\
0&0&0&\sigma^2_2&0&0\\
0&0&0&0&\sigma^2_1&0\\ 
0&0&0&0&0&\sigma^2_2 \\
\end{pmatrix}=\begin{pmatrix}
400&0&0&0&0&0 \\ 
0&36&0&0&0&0\\
0&0&400&0&0&0\\
0&0&0&36&0&0\\
0&0&0&0&400&0\\ 
0&0&0&0&0&36 \\
\end{pmatrix}$


Also, the linear measurement model is $\mathbf{y} = \mathbf{H}x+\mathbf{v}$. The size of $\mathbf{H}$ would be $6\times 1$ as there are six measurements and one parameters. This would be an identity matrix as below:

$ \mathbf{H} = \begin{pmatrix}1\\1\\1\\1\\1\\1\\ \end{pmatrix}$  
and the $\mathbf{y}$ is given by;  $\mathbf{y} = \begin{pmatrix}1048\\992\\1074\\988\\960\\1008\\ \end{pmatrix}$

Now we can use the follwoing expression to find the best **weighted** estimate of the resistance, $\hat{\mathbf{x}}$:  
$\hat{\mathbf{x}} = \left(\mathbf{H^TR^{-1}H}\right)^{-1}\mathbf{H^TR^{-1}y}$

In [32]:
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt

# Store the voltage and current data as column vectors.
H = np.ones((6, 1)).reshape(6,1)
y = np.array([[1048, 992, 1074, 988, 960, 1008]]).T

In [33]:
x_ls = inv(H.T.dot(H)).dot(H.T).dot(y)
print('The Resistance R :')
print(x_ls)

The Resistance R :
[[1011.66666667]]


###Generating Covariance Matrix

In [34]:
R=np.diag(np.full(6,400))
R[1,1]=R[3,3]=R[5,5]=36
print(R)

[[400   0   0   0   0   0]
 [  0  36   0   0   0   0]
 [  0   0 400   0   0   0]
 [  0   0   0  36   0   0]
 [  0   0   0   0 400   0]
 [  0   0   0   0   0  36]]


In [35]:
x_ls = inv((H.T.dot(inv(R)).dot(H))).dot((H.T).dot(inv(R))).dot(y)
print('The Resistance R :')
print(x_ls)

The Resistance R :
[[998.58715596]]
